meta:
  title: "Background Paper: Financial Sector Cyber Security Strategy"
  subtitle: "Inter‑Ministerial Group – Draft for Consultation"
  author: "Department of Economic Affairs, Ministry of Finance"
  date: "September 2025"
  version: "v0.1"
  classification: "Restricted"
  toc: true
  bibliography: true
  bibfile: "bib/references.bib"
